### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by sophiessa** [flyyyxxxy/dgis_flutter#1]
Hi flyyyxxxy,

I also want to make 2gis map available for flutter. Could you leave your contacts so we can collaborate on this matter.

best

**Comment by flyyyxxxy** [comment]
Hello , where are you from? 17:54, 31 мая 2022 г., Sophiessa Philipp ***@***.***>:
Hi flyyyxxxy,
I also want to make 2gis map available for flutter. Could you leave your contacts so we can collaborate on this matter.
best

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flyyyxxxy** [comment]
t.me/flyyyxxxy
